Switch to new scripts and ci stuff

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -15,34 +15,60 @@ RUN <<-EOT
   sudo apt-get update
 
   sudo apt-get install --yes --no-install-recommends \
+    build-essential \
     curl \
     dnsutils \
+    gcc \
     gnupg2
 EOT
 
-# Install additional packages with pipx.
-RUN <<-EOT
-	set -eux
+# # Set up Homebrew.errr
+# RUN <<-EOT
+#   set -eux
 
-  pipx --version
+#   export NONINTERACTIVE=1
 
-	pipx install \
-    copier \
-    pre-commit \
-    uv
-EOT
+#   installer=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
 
-# Install Task with the official installer.
-# Set up completion in Bash.
-RUN <<-EOT
-	set -eux
+#   bash -c "$(curl --location --silent --show-error --fail $installer)"
 
-  curl --location --silent --show-error --fail \
-    https://taskfile.dev/install.sh \
-    | sh -s -- -b ~/.local/bin
+#   echo >> /home/vscode/.bashrc
 
-  ~/.local/bin/task --version
+#   echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' \
+#     >> /home/vscode/.bashrc
+# EOT
 
-  ~/.local/bin/task --completion bash \
-    > ~/.local/share/bash-completion/completions/task
-EOT
+
+
+
+
+
+
+
+
+# # Install additional packages with pipx.
+# RUN <<-EOT
+# 	set -eux
+
+#   pipx --version
+
+# 	pipx install \
+#     copier \
+#     pre-commit \
+#     uv
+# EOT
+
+# # Install Task with the official installer.
+# # Set up completion in Bash.
+# RUN <<-EOT
+# 	set -eux
+
+#   curl --location --silent --show-error --fail \
+#     https://taskfile.dev/install.sh \
+#     | sh -s -- -b ~/.local/bin
+
+#   ~/.local/bin/task --version
+
+#   ~/.local/bin/task --completion bash \
+#     > ~/.local/share/bash-completion/completions/task
+# EOT
